export const data6 = [
  {
    query: "coffee shop, 34337, Beşiktaş, İstanbul, TR",
    name: "Roastico - Coffee Shop & Bar",
    site: "http://www.roastico.com/",
    type: "Kahve dükkanı",
    subtypes: "Kahve dükkanı, Kafe, Kahve Toptancısı, Pub",
    category: "kafeler",
    phone: "+90 212 280 28 88",
    full_address:
      "Nisbetiye, Kerem Apartmanı, Aytar Cd. 27/C, 34000 Beşiktaş/İstanbul",
    borough: "Nisbetiye",
    street: "Kerem Apartmanı, Aytar Cd. 27/C",
    city: "TR",
    postal_code: 34000,
    state: "İstanbul",
    us_state: null,
    country: "Turkey",
    country_code: "TR",
    latitude: 41.0754686,
    longitude: 29.0191882,
    time_zone: "Europe/Istanbul",
    plus_code: null,
    area_service: false,
    rating: 4.8,
    reviews: 74.0,
    reviews_link: null,
    reviews_tags: null,
    reviews_per_score: null,
    reviews_per_score_1: 2.0,
    reviews_per_score_2: 0.0,
    reviews_per_score_3: 2.0,
    reviews_per_score_4: 4.0,
    reviews_per_score_5: 66.0,
    photos_count: 60.0,
    photo:
      "https://lh5.googleusercontent.com/p/AF1QipN49g8gPXXzA__06agZXiNjSAMp0j4eRd0h0Gr_=w800-h500-k-no",
    street_view:
      "https://lh5.googleusercontent.com/p/AF1QipN49g8gPXXzA__06agZXiNjSAMp0j4eRd0h0Gr_=w1600-h1000-k-no",
    located_in: null,
    working_hours: {
      Pazartesi: "07:00-00:00",
      Salı: "07:00-00:00",
      Çarşamba: "07:00-00:00",
      Perşembe: "07:00-00:00",
      Cuma: "07:00-00:00",
      Cumartesi: "08:00-00:00",
      Pazar: "09:00-22:00",
    },
    working_hours_old_format:
      "Pazartesi:07:00-00:00|Salı:07:00-00:00|Çarşamba:07:00-00:00|Perşembe:07:00-00:00|Cuma:07:00-00:00|Cumartesi:08:00-00:00|Pazar:09:00-22:00",
    other_hours: null,
    popular_times: null,
    business_status: "OPERATIONAL",
    about: {
      "Hizmet seçenekleri": {
        "Açık hava bölümü": true,
        "Arabaya teslim alma": true,
        "Temassız teslimat": true,
        "Adrese servis": true,
        "Paket servisi": true,
        "İçeride servis": true,
      },
      "Öne çıkanlar": { "Terasta oturma alanı": true },
      Sunulanlar: {
        Alkol: true,
        "Alkollü içecekler için indirimli saatler": true,
        Bira: true,
        Kahve: true,
        Kokteyller: true,
        "Sert likör": true,
        Şarap: true,
        "Vejetaryenlere yönelik seçenekler": true,
      },
      "Yemek seçenekleri": {
        Kahvaltı: true,
        Tatlı: true,
        "Oturma alanı": true,
      },
      "Sunulan olanaklar": {
        Bar: true,
        Kablosuz: true,
        "Kablosuz ağ bağlantısı": true,
        Tuvalet: true,
        "Üniseks tuvalet": true,
      },
      Atmosfer: { "Günlük kıyafet": true, Rahat: true },
      Kitle: { "Aileler için uygun": true, Gruplar: true },
      Ödeme: {
        "Banka kartı": true,
        "Kredi kartı": true,
        "NFC ile mobil ödeme": true,
      },
    },
    range: null,
    posts: null,
    logo: "https://lh5.googleusercontent.com/-eUN9nW07LYY/AAAAAAAAAAI/AAAAAAAAAAA/cXlz78V5QKY/s44-p-k-no-ns-nd/photo.jpg",
    description: null,
    typical_time_spent: null,
    verified: true,
    owner_id: 116226537736980576316,
    owner_title: "Roastico - Coffee Shop & Bar",
    owner_link: "https://www.google.com/maps/contrib/116226537736980576316",
    reservation_links: null,
    booking_appointment_link: null,
    menu_link: null,
    order_links: null,
    location_link:
      "https://www.google.com/maps/place/Roastico+-+Coffee+Shop+%26+Bar/@41.0754686,29.0191882,14z/data=!4m8!1m2!2m1!1sRoastico+-+Coffee+Shop+%26+Bar!3m4!1s0x14cab641db300001:0x44c8971038a992df!8m2!3d41.0754686!4d29.0191882",
    place_id: "ChIJAQAw20G2yhQR35KpOBCXyEQ",
    google_id: "0x14cab641db300001:0x44c8971038a992df",
    cid: 4956377485847139039,
    reviews_id: 4956377485847139039,
    located_google_id: null,
  },
  {
    query: "coffee shop, 34337, Beşiktaş, İstanbul, TR",
    name: "Coffeeshop Company",
    site: null,
    type: "Kahve dükkanı",
    subtypes: "Kahve dükkanı",
    category: "kafeler",
    phone: null,
    full_address: "Sinanpaşa, Büyükdere Cd. No 181, 34394 Beşiktaş/İstanbul",
    borough: "Sinanpaşa",
    street: "Büyükdere Cd. No 181",
    city: "TR",
    postal_code: 34394,
    state: "İstanbul",
    us_state: null,
    country: "Turkey",
    country_code: "TR",
    latitude: 41.077424,
    longitude: 29.0120762,
    time_zone: "Europe/Istanbul",
    plus_code: null,
    area_service: false,
    rating: 3.1,
    reviews: 12.0,
    reviews_link: null,
    reviews_tags: null,
    reviews_per_score: null,
    reviews_per_score_1: 5.0,
    reviews_per_score_2: 0.0,
    reviews_per_score_3: 0.0,
    reviews_per_score_4: 3.0,
    reviews_per_score_5: 4.0,
    photos_count: 25.0,
    photo:
      "https://lh5.googleusercontent.com/p/AF1QipNZA4e4-HENdyJudCxXfQ0arQUASxkUo64vyhkU=w800-h500-k-no",
    street_view:
      "https://lh5.googleusercontent.com/p/AF1QipNZA4e4-HENdyJudCxXfQ0arQUASxkUo64vyhkU=w1600-h1000-k-no",
    located_in: null,
    working_hours: null,
    working_hours_old_format: null,
    other_hours: null,
    popular_times: null,
    business_status: "OPERATIONAL",
    about: {
      "Hizmet seçenekleri": {
        "Paket servisi": true,
        "İçeride servis": true,
      },
      Sunulanlar: { Kahve: true },
      "Yemek seçenekleri": { Tatlı: true },
      "Sunulan olanaklar": { Tuvalet: true },
      Atmosfer: { "Günlük kıyafet": true, Rahat: true },
    },
    range: "\u20ba\u20ba",
    posts: null,
    logo: null,
    description: null,
    typical_time_spent: null,
    verified: false,
    owner_id: "None",
    owner_title: "Coffeeshop Company",
    owner_link: null,
    reservation_links: null,
    booking_appointment_link: null,
    menu_link: null,
    order_links: null,
    location_link:
      "https://www.google.com/maps/place/Coffeeshop+Company/@41.077424,29.0120762,14z/data=!4m8!1m2!2m1!1sCoffeeshop+Company!3m4!1s0x14cab642a43dffdd:0x6bea769b8afafc4b!8m2!3d41.077424!4d29.0120762",
    place_id: "ChIJ3f89pEK2yhQRS_z6ipt26ms",
    google_id: "0x14cab642a43dffdd:0x6bea769b8afafc4b",
    cid: 7776158117032295499,
    reviews_id: 7776158117032295499,
    located_google_id: null,
  },
  {
    query: "coffee shop, 34337, Beşiktaş, İstanbul, TR",
    name: "Etieler splounge cofe",
    site: null,
    type: "Kahve dükkanı",
    subtypes: "Kahve dükkanı",
    category: "kafeler",
    phone: null,
    full_address: "Etiler, Nisbetiye Cd No:89, 34337 Beşiktaş/İstanbul",
    borough: "Etiler",
    street: "Nisbetiye Cd No:89",
    city: "TR",
    postal_code: 34337,
    state: "İstanbul",
    us_state: null,
    country: "Turkey",
    country_code: "TR",
    latitude: 41.0805094,
    longitude: 29.0337072,
    time_zone: "Europe/Istanbul",
    plus_code: null,
    area_service: false,
    rating: null,
    reviews: null,
    reviews_link: null,
    reviews_tags: null,
    reviews_per_score: null,
    reviews_per_score_1: null,
    reviews_per_score_2: null,
    reviews_per_score_3: null,
    reviews_per_score_4: null,
    reviews_per_score_5: null,
    photos_count: 1.0,
    photo:
      "https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=iL0YCH0--BQd6OsyIhmapQ&cb_client=search.gws-prod.gps&w=800&h=500&yaw=303.51678&pitch=0&thumbfov=100",
    street_view:
      "https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=iL0YCH0--BQd6OsyIhmapQ&cb_client=search.gws-prod.gps&w=1600&h=1000&yaw=303.51678&pitch=0&thumbfov=100",
    located_in: null,
    working_hours: null,
    working_hours_old_format: null,
    other_hours: null,
    popular_times: null,
    business_status: "OPERATIONAL",
    about: {
      "Hizmet seçenekleri": { "İçeride servis": true },
      Sunulanlar: { Kahve: true },
      "Yemek seçenekleri": { Tatlı: true },
      "Sunulan olanaklar": { Tuvalet: true },
      Atmosfer: { "Günlük kıyafet": true, Rahat: true },
      Kitle: { Gruplar: true },
      Çocuklar: { "Çocuklar için uygun": true },
    },
    range: null,
    posts: null,
    logo: null,
    description: null,
    typical_time_spent: null,
    verified: false,
    owner_id: "None",
    owner_title: "Etieler splounge cofe",
    owner_link: null,
    reservation_links: null,
    booking_appointment_link: null,
    menu_link: null,
    order_links: null,
    location_link:
      "https://www.google.com/maps/place/Etieler+splounge+cofe/@41.0805094,29.0337072,14z/data=!4m8!1m2!2m1!1sEtieler+splounge+cofe!3m4!1s0x14cab74556a6bdbf:0xe3e74961b6d66e15!8m2!3d41.0805094!4d29.0337072",
    place_id: "ChIJv72mVkW3yhQRFW7WtmFJ5-M",
    google_id: "0x14cab74556a6bdbf:0xe3e74961b6d66e15",
    cid: 16422175250257964565,
    reviews_id: "None",
    located_google_id: null,
  },
];
